baseURL: "https://kyzy540.github.io/"
languageCode: "en-us"
title: "低质量随笔"
theme: "hugo-PaperMod"

enableInlineShortcodes: true

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: Tags
      url: tags/
      weight: 1
    - name: Archive
      url: archives/
      weight: 2
    - name: Search
      url: search/
      weight: 3

params:
  author: kyzy540
  env: production
  ShowCodeCopyButtons: true
  homeInfoParams:
    Content: "主观，不负责，图一乐 [💬](/post/githubpage_blog_guide)"

outputs:
  home:
    - HTML
    - RSS
    - JSON